version: "3"
services:
  mysql:
    image: mysql
    container_name: spikemysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "mydb"
    volumes:
      - mysqldp
volumes:
  mysqldp: